---
name: Build stretch

on:
  pull_request:
  push:
    paths:
      - 'stretch/**'
      - '.github/workflows/build-stretch.yml'
  schedule:
    - cron: '10 4,9 * * *'
  workflow_dispatch:

jobs:
  # Test the image builds and works correctly.
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test building image.
        run: cd stretch && docker build -t debian-stretch .

      - name: Run the built image.
        run: docker run --name test-stretch -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro debian-stretch

      - name: Verify Ansible is accessible in the built image.
        run: docker exec --tty test-stretch env TERM=xterm ansible --version

  # If on master branch, build and release image.
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: stretch/
          file: stretch/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ github.repository }}:debian-9, ${{ github.repository }}:stretch
