---
name: Build experimental

on:
  push:
    paths:
      - 'sid/**'
      - '.github/workflows/build-sid.yml'
  schedule:
    - cron: '10 5,9 * * *'
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: 'false'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  # Test the image builds and works correctly.
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test building image.
        run: cd sid && docker build -t debian-sid .

      - name: Run the built image.
        run: docker run --name test-sid -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro debian-sid

      - name: Verify Ansible is accessible in the built image.
        run: docker exec --tty test-sid env TERM=xterm ansible --version

  # If on master branch, build and release image.
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: sid/
          file: sid/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ github.repository }}:sid, ${{ github.repository }}:experimental
