---
name: Build buster

on:
  pull_request:
  push:
    paths:
      - 'buster/**'
      - '.github/workflows/build-buster.yml'
  schedule:
    - cron: '20 6,8 * * *'
  workflow_dispatch:

jobs:
  # Test the image builds and works correctly.
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test building image.
        run: cd buster && docker build -t debian-buster .

      - name: Run the built image.
        run: docker run --name test-buster -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro debian-buster

      - name: Verify Ansible is accessible in the built image.
        run: docker exec --tty test-buster env TERM=xterm ansible --version

  # If on master branch, build and release image.
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: buster/
          file: buster/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ github.repository }}:debian-10, ${{ github.repository }}:buster
