---
name: Build jessie

on:
  pull_request:
  push:
    paths:
      - 'jessie/**'
      - '.github/workflows/build-jessie.yml'
  schedule:
    - cron: '40 *,* * * *'
  workflow_dispatch:

jobs:
  # Test the image builds and works correctly.
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test building image.
        run: cd jessie && docker build -t debian-jessie .

      - name: Run the built image.
        run: docker run --name test-jessie -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro debian-jessie

      - name: Verify Ansible is accessible in the built image.
        run: docker exec --tty test-jessie env TERM=xterm ansible --version

  # If on master branch, build and release image.
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: jessie/
          file: jessie/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ github.repository }}:debian-8, ${{ github.repository }}:jessie
